### PR TITLE
dwm 6.2

### PR DESCRIPTION
**Pull request by martin-paulus**
This PR ports the Qubes OS and systray patches to dwm tag 6.2

### CODE REVIEW

**Comment by raffaeleflorio** [comment]
Hi,
first of all **thanks** and sorry for the late reply..
There are few things to do, before the merge:
- [ ] This [rule](https://github.com/martin-paulus/qubes-dwm/blob/1cb83ef88bef98c1d317f8e452ba5e2b6984ba00/dwm-qubes.patch#L52), in Qubes 4.0, shouldn't be needed anymore. For the same reason the [Q tag](https://github.com/raffaeleflorio/qubes-dwm/blob/7933c87adae3ea0c9a7d4ad150ab0a187df2028d/dwm.patch#L38) should be removed.
- [ ] This [line](https://github.com/martin-paulus/qubes-dwm/blob/1cb83ef88bef98c1d317f8e452ba5e2b6984ba00/dwm-qubes.patch#L16) should be in the systray patch because it's related to the systray. As you can see it's [here](https://github.com/raffaeleflorio/qubes-dwm/blob/7933c87adae3ea0c9a7d4ad150ab0a187df2028d/dwm-systray-20171101-6aa8e37.diff#L12) in my old patch.
- [ ] I cannot try in Qubes 4.0 right now, have you tried it on Qubes 4.0? Did you find any issues?

Thanks again!

**Comment by martin-paulus** [comment]
> Hi,
> first of all **thanks** and sorry for the late reply..
> There are few things to do, before the merge:
> 
> <--snip-->
> 
> 
> Thanks again!

Dear @raffaeleflorio,
This PR is not tested (beyond compilation) yet, but I do have a Qubes v4 OS available now.
Thank you for your in depth review! I will work on the remaining points and report back.

Warning: I might take a week or more to get back to you on this, but I would like to continue

**Comment by raffaeleflorio** [comment]
> > Hi,
> > first of all **thanks** and sorry for the late reply..
> > There are few things to do, before the merge:
> > <--snip-->
> > Thanks again!
> 
> Dear @raffaeleflorio,
> This PR is not tested (beyond compilation) yet, but I do have a Qubes v4 OS available now.
> Thank you for your in depth review! I will work on the remaining points and report back.
> 
Great, looking forward for your report!

> Warning: I might take a week or more to get back to you on this, but I would like to continue
>
Don't worry, take your time..

**Comment by raffaeleflorio** [comment]
Hi @martin-paulus ! :) Do you have some news?

**Comment by martin-paulus** [comment]
UPDATE:

* [x]  This [rule](https://github.com/martin-paulus/qubes-dwm/blob/1cb83ef88bef98c1d317f8e452ba5e2b6984ba00/dwm-qubes.patch#L52), in Qubes 4.0, shouldn't be needed anymore. For the same reason the [Q tag](https://github.com/raffaeleflorio/qubes-dwm/blob/7933c87adae3ea0c9a7d4ad150ab0a187df2028d/dwm.patch#L38) should be removed.

* [x]  This [line](https://github.com/martin-paulus/qubes-dwm/blob/1cb83ef88bef98c1d317f8e452ba5e2b6984ba00/dwm-qubes.patch#L16) should be in the systray patch because it's related to the systray. As you can see it's [here](https://github.com/raffaeleflorio/qubes-dwm/blob/7933c87adae3ea0c9a7d4ad150ab0a187df2028d/dwm-systray-20171101-6aa8e37.diff#L12) in my old patch.

Started anew in a local branch, so I will have to prepare some more before I can update this PR.

**Comment by raffaeleflorio** [comment]
> UPDATE:
> 
>     * [x]   This [rule](https://github.com/martin-paulus/qubes-dwm/blob/1cb83ef88bef98c1d317f8e452ba5e2b6984ba00/dwm-qubes.patch#L52), in Qubes 4.0, shouldn't be needed anymore. For the same reason the [Q tag](https://github.com/raffaeleflorio/qubes-dwm/blob/7933c87adae3ea0c9a7d4ad150ab0a187df2028d/dwm.patch#L38) should be removed.
> 
>     * [x]   This [line](https://github.com/martin-paulus/qubes-dwm/blob/1cb83ef88bef98c1d317f8e452ba5e2b6984ba00/dwm-qubes.patch#L16) should be in the systray patch because it's related to the systray. As you can see it's [here](https://github.com/raffaeleflorio/qubes-dwm/blob/7933c87adae3ea0c9a7d4ad150ab0a187df2028d/dwm-systray-20171101-6aa8e37.diff#L12) in my old patch.
> 
> 
> Started anew in a local branch, so I will have to prepare some more before I can update this PR.

Ok, thanks. Looking forward the PR.

**Comment by raffaeleflorio** [comment]
Hi @martin-paulus , are you currently working on it?

**Comment by blackva** [comment]
Hey @raffaeleflorio , what's not finished with this PR that prevents you from merging it?

**Comment by raffaeleflorio** [comment]
Hi! :D
I cannot find your reply on github...
The main issue is that I cannot try the patch on Qubes OS. If you can test it, I can merge manually.

Thanks in advance.

Regards,
Raffaele Florio.

-------- Original Message --------

**Comment by ghost** [comment]
Hey! Sorry for a late reply. When I posted my comment, I noticed that the pull request is one year old and I decided to remove it, not expecting to get a reply. Clearly not the best decision I ever made.

I tested your dwm and this one, but neither of them work. The dwm in official repo doesn't work as well. I briefly described the issue [here](https://github.com/QubesOS/qubes-issues/issues/5966).

**Pull request closed without merging**
