### PR TITLE
update dwm for qubes 4

### PR DESCRIPTION
**Pull request by jampe**
- add some sensible helper scripts to make interaction with qubes easier

### CODE REVIEW

**Comment by jampe** [comment]
commit signed

**Comment by raffaeleflorio** [comment]
Hi @jampe ,
Thank you for this contribution! I'm going to review the patch.

Thank you again!

**Review by raffaeleflorio — COMMENTED** [review]
@jampe What's the version of the systray patch? I think it's useful to track like https://dwm.suckless.org/patches/systray/

**Comment by raffaeleflorio** [comment]
@jampe hello, I think this contribution is really important. Can you address the issue about the systray version? Thanks!

**Comment by jampe** [comment]
sorry I kinda forgot about this. I've renamed the patch accordingly. I've also added a small note to the readme to make everyone aware that it's working on 4.0.x / 4.1.x.

cheers

**Comment by raffaeleflorio** [comment]
I've just merged it, thanks!

**Pull request merged**
